openapi: "3.0.0"
info:
  title: "Match<IT> API"
  description: |
    Documentação da API utilizada no aplicativo Sebrae.
  version: "0.0.1"

servers:
  - url: "http://localhost:5000"
    description: Auth Server. Use este para obter o access token.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

paths:
  /auth:
    post:
      summary: Gerar um Bearer Token
      tags:
        - Autenticação
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  example: 123456
              required:
                - username
                - password
      responses:
        "200":
          description: Token gerado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: seu_token_aqui
                  token_type:
                    type: string
                    example: Bearer
                  expires_in:
                    type: integer
                    example: 3600
        "400":
          description: Requisição inválida - username ou password ausentes
        "401":
          description: Não autorizado - credenciais inválidas
