name: CI Workflow

on:
  push:
    branches:
      - feature/*

jobs:
  integration:
    name: Call CI Workflow
    uses: Mauricio-Camilo/ci-cd-pipelines/.github/workflows/ci.yml@main
    secrets: inherit