name: Quality Workflow

on:
  pull_request:
    branches:
      - development

jobs:
  quality_call:
    name: Call CI Workflow
    uses: Mauricio-Camilo/ci-cd-pipelines/.github/workflows/quality.yml@main
    secrets: inherit
